import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import ThemeRegistry from "@/theme";
import { ThemeToggleProvider } from "@/contexts/themeToggleContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <ThemeToggleProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </ThemeToggleProvider>
      </body>
    </html>
  );
}
